language: android

# Specify jdk to run lambda expression
jdk: oraclejdk8

env:
  global:
   # Encrypted `CODACY_PROJECT_TOKEN` variable according to:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    -secure: xuIB1RtI4tSQI9IM9Bvs7DngGZoYt2GG2pRYDiVcENhpvAgTspxNZZsBubwnbAu149wnemd4uuy6P3GgUXsNbo/6hqq+nnd04zwTZivnCBjW9zJrcH611W+nwITszcBC1LBpgH00a9flhDdWyZ08E9i9UZygrGC60G7BPRbFp5g+MHMElJbPnkkKL9XlT1Xjy3qADZyH7n1mkQ+zw9Wg0i6FKeWxl/DUx7DHOi/Ve5bIwm6uqLwp6BC9++uslw4Z6P3xWjd63PUdfDCWs4hUr5/y0MioflX7885bVgL0u60f1Z0apBxTLcx3hLeq1UEfBrwUQGL8kiRMOtmzjzFIK7VQXNEBa0j/gliSDTdBXF6zGdy22PQ7MaKdW/dq7XKhXzYgivbiooxXl6tAx2C99WSWdf3+aGUqho3/kuL0q6G4yFTEQ0pbMUYlvoq8//tTT4h4fKGzD/NMavAiEAuLcVguEbUKz0jroFNn1gIN/Ph+jQ9eutQ//NOViDiRp872H/ztymGeKMpMFrNCIag2U0uDiQsAZjtZQF1bdUF5rNkrTFMOHtg5nuhUdiIDdV6yzDnUWUpY5LH6B8vyWBXR1IlSlaK2af+TEy4TP8HZIL1af/GMERBltZutSVtpyzl95a1PDxUSeT+PnasCakeuwCmFU1lyG4jbo+PtgrDkS48=
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a
    
    
android:
  components:
    - tools
    - build-tools-25.0.1
    - android-25
    # Google repositories
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    # - extra-google-google_play_services
    # Ressource(s) to run emulator during test
    - sys-img-armeabi-v7a-android-25
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  # Codacy setup. See: https://github.com/codacy/codacy-coverage-reporter#travis-ci
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
    # END of Codacy setup.

# Build
script:
  - ./gradlew check

after_success:
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh
